### ISSUE TITLE
fails on builder step

### ISSUE THREAD

**Issue by paulpach** [webbertakken/unity-actions#23]
Here is my config:

```
on: [push]

jobs:

  testRunnerInAllModes:
    name: Unity test
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1

      - run: ls -l
        
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v0.3
        with:
          projectPath: "."
          unityVersion: "2019.2.11f1"
          buildCommand: "UnityEditor.SyncVS.SyncSolution"
          targetPlatform: StandaloneWindows64

```

I am getting this error message when it gets to Unity - Builder step:
```
 Generate Solution0s
##[error]Node run failed with exit code 1
Run webbertakken/unity-builder@v0.3
/usr/bin/docker build /home/runner/work/MirrorNG/MirrorNG --file /home/runner/work/MirrorNG/MirrorNG/Dockerfile --build-arg IMAGE=gableroux/unity3d:2019.2.11f1-windows --tag unity-builder:2019.2.11f1-windows
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/MirrorNG/MirrorNG/Dockerfile: no such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1
##[error]Node run failed with exit code 1
```

Here is a link to the failed job:
https://github.com/MirrorNG/MirrorNG/commit/70cd06ab6fa3f7ec7d00fdf1a37608245405a12a/checks?check_suite_id=380753696

**Comment by paulpach** [comment]
Here is an update,  v0.2 works fine with the exact same configuration,  it seems this is a regression in v0.3

**Comment by webbertakken** [comment]
> Here is an update, v0.2 works fine with the exact same configuration, it seems this is a regression in v0.3

Hi @paulpach,

Thanks for reporting the issue. I'll have a look when I get the chance.

Please note that v0.2 has a different readme and did not allow for builds other than from the webgl image at all. A lot has changed since.

See also the progress on supporting multiple platforms here https://github.com/webbertakken/unity-actions/issues/12

**Comment by webbertakken** [comment]
Work can be tracked here: https://github.com/webbertakken/unity-builder/pull/9

**Comment by webbertakken** [comment]
This is fixed in https://github.com/webbertakken/unity-builder/pull/10

As can also be seen here: https://github.com/webbertakken/unity-actions/pull/24/checks?check_run_id=376523913

**Comment by Rabadash8820** [comment]
I was also getting this error when targeting Android on Unity 2019.2.17f1. Any idea when this fix will be deployed?

**Comment by webbertakken** [comment]
Please note that I'm doing all this just in my free time, while my real goal in that time is creating a unity project. That said, I'll do what I can do. Could you please try it on v0.4 and create a new issue for it and show the error?

**Comment by Rabadash8820** [comment]
@webbertakken That seems to have fixed it 🙂 I'm still getting build errors, but it looks like now its because there's no gableroux/unity3d Dockerfile for Unity 2019.2.17f1 yet. Guess my next Issue/PR will be over there lol

**Comment by GabLeRoux** [comment]
@Rabadash8820 already done ;) https://gitlab.com/gableroux/unity3d/merge_requests/77

**Comment by Rabadash8820** [comment]
@GabLeRoux Awesome! And damn, impressive following of other repos' Issues 😛
